name: Deploy
on:
  push:
    branches:
      - 'master'

jobs:
  deploy_to_usin:
    runs-on: ubuntu-latest
    env:
      deployment_server: ${{ secrets.DEPLOYMENT_SERVER1 }}
      deployment_token: ${{ secrets.DEPLOYMENT_TOKEN1 }}
    steps:
      - name: Webhook
        run: ./deploy_request.sh
        working-directory: .github/workflows/

  deploy_to_monomakh:
    runs-on: ubuntu-latest
    env:
      deployment_server: ${{ secrets.DEPLOYMENT_SERVER2 }}
      deployment_token: ${{ secrets.DEPLOYMENT_TOKEN2 }}
    steps:
      - name: Webhook
        run: ./deploy_request.sh
        working-directory: .github/workflows/
