name: Deploy
on:
  push:
    branches:
      - 'master'

jobs:
  deploy_to_usin:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to server
        run: |
          curl --silent --show-error --fail -X POST ${{ secrets.DEPLOYMENT_SERVER1 }} \
          -H 'Authorization: ${{ secrets.DEPLOYMENT_TOKEN1 }}' -H 'Content-Type: application/json' \
          -d '{"project_name": "webhook_shell_invoker"}' \
          || if [ "$?" -eq 52 ]; then true; else false; fi # Ignore empty reply from server (self-restart)

  deploy_to_monomakh:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to server
        run: |
          curl --silent --show-error --fail -X POST ${{ secrets.DEPLOYMENT_SERVER2 }} \
          -H 'Authorization: ${{ secrets.DEPLOYMENT_TOKEN2 }}' -H 'Content-Type: application/json' \
          -d '{"project_name": "webhook_shell_invoker"}' \
          || if [ "$?" -eq 52 ]; then true; else false; fi # Ignore empty reply from server (self-restart)
